export const GET_STATES_REQUEST="GET_STATES_REQUEST";
export const GET_STATES_SUCCESS="GET_STATES_SUCCESS";
export const GET_STATES_FAILURE="GET_STATES_FAILURE";

export const GET_CITIES_REQUEST="GET_CITIES_REQUEST";
export const GET_CITIES_SUCCESS="GET_CITIES_SUCCESS";
export const GET_CITIES_FAILURE="GET_CITIES_FAILURE";

